### ISSUE TITLE
Locking grid size and resize map instead

### ISSUE THREAD

**Issue by MMetze** [MMetze/DMHelper-Tracker#89]
**Discord User:**
@GreenTentacle

**Describe the solution you'd like**
When using a display as digital map, it would be nice to once scale the grid to a physical size
on the screen. If that is done, the scale between the map and miniatures would be correct and 
stay the same, throughout map zooming, moving, changing view, ...
This could be a value for the settings and an option (checkbox) to use it in map-mode.
If checked, the grid-size in the player view would always stay the same and instead the map would get scaled, or moved.

**Comment by DrkNinja** [comment]
This is already an issue...

**Comment by MMetze** [comment]
https://github.com/MMetze/DMHelper-Tracker/issues/24

**Comment by DrkNinja** [comment]
This wasn't ever released? @dm-helper am I crazy here?

**Comment by dm-helper** [comment]
@DrkNinja GT closed this as a duplicate of issue #24. That isn't quite right.

This issue: set a grid size (once) effectively for a given screen/display you have and then any changes in the player camera or zoom or gridsize impact only the zoom level of the map, but never the actual rendered size of the grid. Effectively, this inverts the current grid sizing logic: right now when you change the grid size, the image doesn't change.
This is a really important usability feature for anybody playing with minis on a screen.

Issue #24: Set a default grid size that will be used initially for any map instead of the current (semi-random) default value, regardless of whether its locked or not
